# -*- coding: utf-8; mode: dockerfile; -*-
FROM docker.io/puppet/puppet-bolt:4.0.0
LABEL maintainer="Tom Vaughan <tom@nalca.bio>"

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN DEBIAN_FRONTEND=noninteractive apt -q update                                \
    && apt -q dist-upgrade -y                                                   \
    && apt -q install -y                                                        \
        dumb-init                                                               \
        openssh-client                                                          \
    && apt -q clean                                                             \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /mnt/workdir

ENTRYPOINT ["dumb-init", "--"]

CMD ["bash"]
