#!/bin/sh -e
# -*- coding: utf-8; mode: sh -*-
REGISTRY=ghcr.io
CONTAINER=nalcabio/containers/mosquitto
VERSION=2
CMD=$(basename $0)
podman run --rm -it -v $PWD:/mnt/workdir $REGISTRY/$CONTAINER:$VERSION $CMD "$@"
