# -*- coding: utf-8; mode: dockerfile; -*-
FROM docker.io/library/eclipse-mosquitto:2
LABEL maintainer="Tom Vaughan <tom@nalca.bio>"

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN apk add --no-cache catatonit

WORKDIR /mnt/workdir

ENTRYPOINT ["catatonit", "--"]

CMD ["sh"]
