# -*- coding: utf-8; mode: dockerfile; -*-
FROM docker.io/library/debian:trixie
LABEL maintainer="Tom Vaughan <tom@nalca.bio>"

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN export DEBIAN_FRONTEND=noninteractive                                       \
    && apt -q update                                                            \
    && apt -q dist-upgrade -y                                                   \
    && apt -q install -y                                                        \
        catatonit                                                               \
        curl                                                                    \
        dh-exec                                                                 \
        git                                                                     \
        javahelper                                                              \
        make                                                                    \
        maven                                                                   \
        npm                                                                     \
        openjdk-25-jdk-headless                                                 \
        rlwrap                                                                  \
        ruby-dev                                                                \
        ruby-rubygems                                                           \
        unzip                                                                   \
    && apt -q clean                                                             \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL https://github.com/clj-kondo/clj-kondo/releases/download/v2025.10.23/clj-kondo-2025.10.23-linux-amd64.zip \
        -o clj-kondo.zip                                                      \
    && unzip clj-kondo.zip                                                    \
    && install clj-kondo /usr/local/bin                                       \
    && rm -rf clj-kondo*

RUN curl -sL https://github.com/kkinnear/zprint/releases/download/1.3.0/zprintl-1.3.0 \
        -o zprint                                                               \
    && install zprint /usr/local/bin                                            \
    && rm -rf zprint*

RUN bash -c "$(curl -sL https://download.clojure.org/install/linux-install-1.12.4.1582.sh)"

RUN clojure -Sverbose -M -e '(println (str "Using Clojure: " (clojure-version)))'

WORKDIR /mnt/workdir

ENTRYPOINT ["catatonit", "--"]

CMD ["bash"]

COPY builder/ /var/opt/builder/

ENV CLJ_CONFIG=/var/opt/builder

# https://ask.clojure.org/index.php/12414/set-gitlibs-in-deps-edn
ENV GITLIBS=${CLJ_CONFIG}/gitlibs
