# -*- coding: utf-8; mode: dockerfile; -*-
FROM docker.io/apache/superset:4.1.1
LABEL maintainer="Tom Vaughan <tom@nalca.bio>"

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

COPY local/ /var/opt/superset/

RUN pip install psycopg2-binary==2.9.10 sqlalchemy-parseable==0.1.4
